# Generated by Django 4.2.5 on 2023-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('max_tokens', models.IntegerField()),
                ('compatibility', models.CharField(choices=[('COMPLETION', 'Completion'), ('CHAT_COMPLETION', 'Chat_Completion')], max_length=100)),
            ],
        ),
    ]
