# Generated by Django 4.2.5 on 2023-09-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'verbose_name': 'AI Model'},
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='compatibility',
            field=models.CharField(choices=[('COMPLETION', 'Completion'), ('CHAT_COMPLETION', 'Chat Completion')], max_length=100),
        ),
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('chat_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_chat_responses', to='chatbot.chatquery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatquery',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_chat_queries', to='chatbot.chatsession'),
        ),
    ]
